name: Auto rebase master
on:
  pull_request:
    types:
      - closed

jobs:
  merge-to-master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all branches
        run: git fetch --all

      - name: Get branch names
        id: branch-names
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          branch_names=$(git branch -r --format='%(refname:short)' | sed 's/origin\///g')
          echo "::set-output name=branches::$branch_names"
          
      - name: Fetch and update repository
        run: git fetch origin && git checkout master && git pull origin master

      - name: Merge to Master
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
        run: |
          echo "START git action auto rebase"
          for target_branch in $(git branch -r --format='%(refname:short)' | sed 's/origin\///g'); do
            echo "target branch :"$target_branch
            if [ "$target_branch" != "master" ] && [ "$target_branch" != "HEAD" ]; then
              git checkout $target_branch
              echo "Check out branch :"$target_branch
              # if git merge --no-ff master ; then
              if git rebase origin/master; then
                git push origin/$target_branch
                echo "Rebase successful: $target_branch"
              else
                echo "Conflict occurred: $target_branch"
                # git merge --abort
                git rebase --abort
                git reset --hard origin/$target_branch
              fi
            fi
          done
          echo "FINISH git action auto rebase"
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
