name: Auto rebase develop
on:
  push:
    branches:
      - develop

jobs:
  rebase-to-develop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch --all

      - name: Get branch names
        id: branch-names
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          branch_names=$(git branch -r --format='%(refname:short)' | sed 's/origin\///g')
          echo "$branch_names"

      - name: Rebase to develop
        run: |
          echo "START git action auto rebase"
          for target_branch in $(git branch -r --format='%(refname:short)' | sed 's/origin\///g'); do
            echo "rebase develop target branch: $target_branch"
            if [[ "$target_branch" =~ ^(feature/.*|fix-bug/.*)$ ]]; then
              git checkout $target_branch
              echo "Check out branch: $target_branch"
              # if git merge --no-ff develop ; then
              if git rebase origin/develop; then
                git push --force origin $target_branch
                echo "Rebase successful: $target_branch"
              else
                echo "Conflict occurred: $target_branch"
                # git merge --abort
                git rebase --abort
                git reset --hard origin/$target_branch
                echo "$target_branch" >> conflict_file.tmp
              fi
            fi
          done
          echo "FINISH git action auto rebase"
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Check conflict branch
        run: |
          echo "START check conflict branch"
          if [ -f "./conflict_file.tmp" ]; then
              while read line; do
                echo "::warning file=Conflict::Rebase develop has conflict on branch: $line"
              done < ./conflict_file.tmp
              echo "ERROR conflict branch"
              rm conflict_file.tmp
              exit 1
          fi
          echo "FINISH check conflict branch"
