name: Auto rebase master
on:
  pull_request:
    types:
      - closed

jobs:
  merge-to-master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch --all

      - name: Get branch names
        id: branch-names
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          branch_names=$(git branch -r --format='%(refname:short)' | sed 's/origin\///g')
          echo "::set-output name=branches::$branch_names"
          
      - name: Fetch and update repository
        run: git fetch origin && git checkout master && git pull origin master

      - name: Merge to Master
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'master'
        run: |
          echo "START git action auto rebase"
          git log --all --graph
          git reset --hard HEAD
          git checkout master
          git checkout develop
          git reset --hard HEAD
          git rebase master
          echo "FINISH git action auto rebase"
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
